### ISSUE TITLE
第1675题：怎么让CSS flex布局最后一行列表左对齐？

### ISSUE THREAD

**Issue by front-end-interview-questions** [front-end-interview-questions/front-end-interview-questions#759]
# 前端面试题宝典-第1675题
## justify-content对齐问题描述

在CSS flex布局中，justify-content属性可以控制列表的水平对齐方式，例如space-between值可以实现两端对齐。

但是，如果最后一行的列表的个数不满，则就会出现最后一行没有完全垂直对齐的问题。

如下代码：

```css
.container {
    display: flex;
    justify-content: space-between;
    flex-wrap: wrap;
}
.list {
    width: 24%; height: 100px;
    background-color: skyblue;
    margin-top: 15px;
}
```

```html
<div class="container">
    <div class="list"></div>
    <div class="list"></div>
    <div class="list"></div>
    <div class="list"></div>
    <div class="list"></div>
    <div class="list"></div>
    <div class="list"></div>
</div>
```

![image.png](https://ae04.alicdn.com/kf/Hf1a4fff1d2894f1e9abe1106afa1ebd9R.png)

怎么让最后一行左对齐呢？
## 微信扫码查看详细解析

![扫码看答案](http://eas.ecool.fun/as/openapi/exercise/qrImage?id=1675&exerciseKey=389a7ca7-43d2-4fbe-99ef-50bea32bef5c&utmSource=github)

## 微信扫码关注【前端面试题宝典】，开启前端专家之路
**前端面试题宝典**，专注 **web前端工程师** 学习、面试，定期分享高质量**前端技术文章**、**前端面试经验**分享
包括各种前端知识点：**JavaScript**、**React.js**、**Vue**、**Node.js**、**前端工程化**、**计算机网络**、**前端安全**、**小程序**等
![前端面试题宝典 公众号二维码](https://i.loli.net/2021/07/17/hVWHjuz1SsfE5qb.jpg)
